spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE} #program arguments로 job.name 값이 넘어오면, 해당 값과 일치하는 Job만 실행

---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: tester
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver